# Generated by Django 5.2.6 on 2025-09-13 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alert_checklistsection_drillstep_employee_industry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_domain', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='DrillStep',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.DeleteModel(
            name='TrainingQuestion',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.AlterField(
            model_name='checklistquestion',
            name='question_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checklistsection',
            name='sectionKey',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='checklistsection',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_sections', to='core.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanfinding',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scan_findings', to='core.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='checklistsection',
            unique_together={('user_profile', 'sectionKey')},
        ),
    ]
